# Generated by Django 5.2.1 on 2025-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='day_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
